### PR TITLE
hello home! pt1

### PR DESCRIPTION
**Pull request by jcherrera**

### CODE REVIEW

**Comment by FredLoh** [comment]
We don't want to call script(src='https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/js/materialize.min.js')

Since we're using bower to serve it

**Comment by jcherrera** [comment]
@FredLoh I'll remove it on my next commit, I needed it for testing purposes since bower was giving errors.

**Comment by FredLoh** [comment]
:+1:

**Comment by jcherrera** [comment]
:+1:

**Comment by jcherrera** [comment]
:+1:

**Pull request merged**
